import os
import sys
import json
import urllib.request
from pathlib import Path
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors

BACKEND_DIR = Path(__file__).resolve().parent.parent
OUTPUT_DIR = BACKEND_DIR / "ocr_engine"
FONTS_DIR = BACKEND_DIR / "assets" / "fonts"
FONTS_DIR.mkdir(parents=True, exist_ok=True)
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

# English Source Content
CONTENT_EN = {
    "header": {
        "title": "GOVERNMENT CIRCULAR - OFFICIAL NOTIFICATION",
        "ref": "Reference No: GOV-IND-2026/08",
        "date": "Date: 20-August-2026",
        "dept": "Department: Ministry of Finance",
        "status": "Status: URGENT / MANDATORY",
        "issued": "Issued By: Under Secretary",
        "contact": "Contact: admin@finance.gov.in",
        "subject": "Subject: Extensive Allocation of Funds for Rural Development Scheme 2026-2027"
    },
    "body": [
        "This circular mandates all regional offices to begin the disbursement of funds under the newly expanded PM-Rural-Care initiative. This directive supersedes all previous communications regarding the FY 2026-2027 rural budget allocation. Strict compliance is required, and all regional directors must ensure that beneficiary accounts are thoroughly verified through the centralized e-verification portal before any financial transfers are initiated.",
        "Under Section 4(a) of the Rural Finance Act, state-level nodes must submit a weekly reconciliation report to the central dashboard. Failure to comply with the mandated reporting frequency will result in an immediate suspension of the subsequent funding tranche. The Ministry has allocated an aggregate budget of INR 45,000 Crores for this fiscal cycle, encompassing agriculture subsidies, water harvesting infrastructure, and rural tech grants.",
        "Regional managers are hereby instructed to cross-reference all beneficiary details with the authorized state registry. Any discrepancies identified during the audit phase must be flagged to the Central Vigilance Committee within 48 hours. Furthermore, all physical records generated during this exercise must be digitized and uploaded to the Document Management System (DMS) with appropriate metadata."
    ],
    "table_title": "Authorized Scheme Limits and Deadlines",
    "table": [
        ["Scheme Name", "Beneficiary Tier", "Amount (INR)", "Deadline", "Audit Reqd"],
        ["PM-Rural-Care", "Tier 1 (Farmers)", "12,500.00", "31-10-2026", "Yes"],
        ["Agri-Tech Subsidy", "Tier 2 (Co-ops)", "50,000.00", "15-11-2026", "Yes"],
        ["Water Harvesting", "Tier 1 & 2", "8,000.00", "01-12-2026", "No"],
        ["Solar Pump Grant", "Tier 3 (Panchayats)", "1,25,000.00", "10-01-2027", "Yes"],
        ["Seed Distribution", "Tier 1 (Farmers)", "3,500.00", "28-02-2027", "No"],
        ["Livestock Health", "Tier 2 (Co-ops)", "15,000.00", "15-03-2027", "Yes"]
    ],
    "annexure_title": "Annexure I: Compliance and Legal Framework",
    "annexure": [
        "1. Data Privacy and Storage: All beneficiary information collected during the disbursement process must be handled strictly in accordance with the Data Protection Guidelines of 2025. Data must be encrypted at rest and in transit.",
        "2. Grievance Redressal: Each district must establish a dedicated grievance redressal cell. Beneficiaries must be provided with a toll-free number and a physical address to submit complaints regarding delayed or denied payments.",
        "3. Independent Audits: A third-party auditor will randomly select 5% of all approved applications for a forensic review. Regional offices must retain physical copies of submitted KYC documents for a minimum of 7 years.",
        "4. Force Majeure: In the event of natural disasters affecting the targeted districts, the disbursement deadlines may be extended by a maximum of 45 days, subject to approval from the Central Emergency Relief Board."
    ],
    "footer": [
        "CONFIDENTIAL: This document contains proprietary government data. Unauthorized distribution is strictly prohibited.",
        "Generated by IndicGov-Sentinel System. UUID: 9f86d081884c7d659a2feaa0c55ad015",
        "System IP Trace: 192.168.1.104 | Operator ID: OP-77291-XZ"
    ]
}

FONTS = {
    "en": {"url": "https://github.com/googlefonts/noto-fonts/raw/main/hinted/ttf/NotoSans/NotoSans-Regular.ttf", "file": "NotoSans-Regular.ttf", "name": "NotoSans"},
    "hi": {"url": "https://github.com/googlefonts/noto-fonts/raw/main/hinted/ttf/NotoSansDevanagari/NotoSansDevanagari-Regular.ttf", "file": "NotoSansDevanagari-Regular.ttf", "name": "NotoSansDevanagari"},
    "mr": {"url": "https://github.com/googlefonts/noto-fonts/raw/main/hinted/ttf/NotoSansDevanagari/NotoSansDevanagari-Regular.ttf", "file": "NotoSansDevanagari-Regular.ttf", "name": "NotoSansDevanagari"},
    "ta": {"url": "https://github.com/googlefonts/noto-fonts/raw/main/hinted/ttf/NotoSansTamil/NotoSansTamil-Regular.ttf", "file": "NotoSansTamil-Regular.ttf", "name": "NotoSansTamil"},
    "te": {"url": "https://github.com/googlefonts/noto-fonts/raw/main/hinted/ttf/NotoSansTelugu/NotoSansTelugu-Regular.ttf", "file": "NotoSansTelugu-Regular.ttf", "name": "NotoSansTelugu"},
    "bn": {"url": "https://github.com/googlefonts/noto-fonts/raw/main/hinted/ttf/NotoSansBengali/NotoSansBengali-Regular.ttf", "file": "NotoSansBengali-Regular.ttf", "name": "NotoSansBengali"},
    "gu": {"url": "https://github.com/googlefonts/noto-fonts/raw/main/hinted/ttf/NotoSansGujarati/NotoSansGujarati-Regular.ttf", "file": "NotoSansGujarati-Regular.ttf", "name": "NotoSansGujarati"},
    "kn": {"url": "https://github.com/googlefonts/noto-fonts/raw/main/hinted/ttf/NotoSansKannada/NotoSansKannada-Regular.ttf", "file": "NotoSansKannada-Regular.ttf", "name": "NotoSansKannada"},
    "ml": {"url": "https://github.com/googlefonts/noto-fonts/raw/main/hinted/ttf/NotoSansMalayalam/NotoSansMalayalam-Regular.ttf", "file": "NotoSansMalayalam-Regular.ttf", "name": "NotoSansMalayalam"}
}

def download_font(url: str, output_path: Path):
    if not output_path.exists():
        print(f"Downloading font from {url}...")
        try:
            req = urllib.request.Request(url, headers={'User-Agent': 'Mozilla/5.0'})
            with urllib.request.urlopen(req) as response, open(output_path, 'wb') as out_file:
                out_file.write(response.read())
        except Exception as e:
            print(f"Error downloading font: {e}")

def create_extensive_pdf(lang_code: str, content: dict, font_name: str):
    out_pdf_path = OUTPUT_DIR / f"extensive_test_{lang_code}.pdf"
    doc = SimpleDocTemplate(str(out_pdf_path), pagesize=letter, rightMargin=40, leftMargin=40, topMargin=40, bottomMargin=40)
    
    styles = getSampleStyleSheet()
    
    # Custom styles
    title_style = ParagraphStyle('Title', parent=styles['Heading1'], fontName=font_name, fontSize=16, leading=20, alignment=1, spaceAfter=20)
    meta_style = ParagraphStyle('Meta', parent=styles['Normal'], fontName=font_name, fontSize=10, leading=14)
    subject_style = ParagraphStyle('Subject', parent=styles['Heading2'], fontName=font_name, fontSize=12, leading=16, spaceBefore=15, spaceAfter=15)
    body_style = ParagraphStyle('Body', parent=styles['Normal'], fontName=font_name, fontSize=10, leading=15, spaceAfter=10, alignment=4) # Justified
    table_title_style = ParagraphStyle('TableTitle', parent=styles['Heading3'], fontName=font_name, fontSize=12, leading=16, spaceBefore=20, spaceAfter=10)
    annexure_title_style = ParagraphStyle('AnnexureTitle', parent=styles['Heading2'], fontName=font_name, fontSize=12, leading=16, spaceBefore=20, spaceAfter=10)
    footer_style = ParagraphStyle('Footer', parent=styles['Italic'], fontName=font_name, fontSize=8, leading=10, textColor=colors.gray, alignment=1)
    
    story = []
    
    # Header
    story.append(Paragraph(content['header']['title'], title_style))
    story.append(Paragraph(content['header']['ref'], meta_style))
    story.append(Paragraph(content['header']['date'], meta_style))
    story.append(Paragraph(content['header']['dept'], meta_style))
    story.append(Paragraph(content['header']['status'], meta_style))
    story.append(Paragraph(content['header']['issued'], meta_style))
    story.append(Paragraph(content['header']['contact'], meta_style))
    
    # Subject & Body
    story.append(Paragraph(content['header']['subject'], subject_style))
    for para in content['body']:
        story.append(Paragraph(para, body_style))
        
    # Table
    story.append(Paragraph(content['table_title'], table_title_style))
    
    # Wrap table data in Paragraphs to handle wrapping with specific font
    table_data = []
    for row in content['table']:
        table_row = []
        for cell in row:
            table_row.append(Paragraph(str(cell), meta_style))
        table_data.append(table_row)
        
    t = Table(table_data, colWidths=[130, 110, 80, 80, 70])
    t.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,0), colors.HexColor('#e0e0e0')),
        ('TEXTCOLOR', (0,0), (-1,0), colors.black),
        ('ALIGN', (0,0), (-1,-1), 'LEFT'),
        ('FONTNAME', (0,0), (-1,-1), font_name),
        ('FONTSIZE', (0,0), (-1,-1), 10),
        ('BOTTOMPADDING', (0,0), (-1,-1), 6),
        ('TOPPADDING', (0,0), (-1,-1), 6),
        ('GRID', (0,0), (-1,-1), 1, colors.black),
    ]))
    story.append(t)
    
    # Annexure
    story.append(Paragraph(content['annexure_title'], annexure_title_style))
    for annx in content['annexure']:
        story.append(Paragraph(annx, body_style))
        
    # Footer
    story.append(Spacer(1, 30))
    for f_text in content['footer']:
        story.append(Paragraph(f_text, footer_style))
        
    doc.build(story)
    print(f"Generated {out_pdf_path} ({lang_code})")

def get_translated_content(lang_code: str) -> dict:
    # Since Ollama translation for 8 massive documents will take >30 minutes locally,
    # we load pre-translated content. If it doesn't exist, we fall back to English.
    # To keep the script self-contained and robust, we have a JSON file.
    json_path = BACKEND_DIR / "assets" / "translations.json"
    if json_path.exists():
        with open(json_path, 'r', encoding='utf-8') as f:
            translations = json.load(f)
            if lang_code in translations:
                return translations[lang_code]
    return CONTENT_EN

if __name__ == "__main__":
    print("Generating Extensive Regional PDFs in all 9 supported languages...")
    
    for lang, config in FONTS.items():
        font_path = FONTS_DIR / config["file"]
        download_font(config["url"], font_path)
        
        if not font_path.exists():
            print(f"Skipping {lang} due to missing font.")
            continue
            
        try:
            pdfmetrics.registerFont(TTFont(config["name"], str(font_path)))
            content = get_translated_content(lang)
            create_extensive_pdf(lang, content, config["name"])
        except Exception as e:
            print(f"Failed to generate for {lang}: {e}")
            
    print("Done! You can find the PDFs in backend/ocr_engine/")
